### ISSUE TITLE
Checkout Error: Sorry, that's an invalid country for VBVSECURECODE

### ISSUE THREAD

**Issue by emzola** [bosunolanrewaju/WooCommerce-Flutterwave-Payment-Gateway#11]
Hello, I seem to be having another problem with the rave woocommerce plugin on my website. This is the error I get when I try to checkout using a visa card and a master card: "Sorry, that's an invalid country for VBVSECURECODE"

However, when I test the checkout button on my Rave dashboard using the same visa card, it processes the payment without any issue. I have looked at my woocommerce settings and everything seems okay. Don't know what the problem is.

**Comment by emzola** [comment]
Dear Bosun, tops! I haven't heard your opinion about this. Just checking.

**Comment by emzola** [comment]
Dear Bosun, while testing the Checkout Button (not the Woocommerce Plugin) this morning, I realized that I still get the same VBV/SECURECODE error on my site when I embed the checkout button to WordPress by copying and pasting the embed code from my Rave dashboard. However, a little tweak to the embed code by changing the "data-country" class from US to NG, whilst leaving the "data-currency" class still set at USD solves the problem. This only works for the pay button. I dunno if this might be useful to you in resolving the issue with the plugin.

**Comment by emzola** [comment]
Dear Bosun, while trying the Checkout Button (not the Woocommerce Plugin) on my website this morning, I realized that I still get the same VBV/SECURECODE error when I embed the checkout button to WordPress by copying and pasting the embed code from my Rave dashboard. However, a little tweak to the embed code by changing the "data-country" class from US to NG, whilst leaving the "data-currency" class still set at USD solves the problem. This only works for the pay button. I dunno if this info might be useful to you in resolving the issue with the woocommerce plugin.

**Comment by bosunolanrewaju** [comment]
@emzola I sincerely apologize for the late response. I didn't get a notification that an issue has been raised for the plugin. And many thanks for going extra length in trying to get a fix. I am aware of the country issue in the plugin. For some reasons I think the country setting gets saved as NG:LA (i.e. <Country ISO code>:<State ISO code>) instead of just NG and it is because I currently use WooCommerce country settings for the plugin.

A quick fix will be to explicitly ask users to set the values, even for the currency within the plugin settings page. This would be done later today and I will let you know when to test.

**Comment by bosunolanrewaju** [comment]
@emzola I just made a fix for the country issue, can you please do a fresh installation from the current master? Let me know if it fixes the issue with VBV/SECURECODE country validity.

**Comment by emzola** [comment]
Thanks very much! It now works. I'm super grateful!

**Comment by bosunolanrewaju** [comment]
Happy to help. Cheers!
